// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPQ3QERybrhPS2sXlfx95tiD8r7Taf-iw',
    appId: '1:145051601496:web:c3e692272cd74b67fd182d',
    messagingSenderId: '145051601496',
    projectId: 'clique-c4bf4',
    authDomain: 'clique-c4bf4.firebaseapp.com',
    storageBucket: 'clique-c4bf4.appspot.com',
    measurementId: 'G-7B23X52T0T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWfi1gfr5sqNHq_5C-bI85HLkceCXcxhk',
    appId: '1:145051601496:android:9e92b0da9d741774fd182d',
    messagingSenderId: '145051601496',
    projectId: 'clique-c4bf4',
    storageBucket: 'clique-c4bf4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkHPqlSc_0uv-dozzunyGBlzoGu-YaegQ',
    appId: '1:145051601496:ios:42b3647cb87930ddfd182d',
    messagingSenderId: '145051601496',
    projectId: 'clique-c4bf4',
    storageBucket: 'clique-c4bf4.appspot.com',
    iosClientId: '145051601496-fcqk1kfac3flrn7s5h5k2hhob3rc1495.apps.googleusercontent.com',
    iosBundleId: 'com.misenpai.clique',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkHPqlSc_0uv-dozzunyGBlzoGu-YaegQ',
    appId: '1:145051601496:ios:42b3647cb87930ddfd182d',
    messagingSenderId: '145051601496',
    projectId: 'clique-c4bf4',
    storageBucket: 'clique-c4bf4.appspot.com',
    iosClientId: '145051601496-fcqk1kfac3flrn7s5h5k2hhob3rc1495.apps.googleusercontent.com',
    iosBundleId: 'com.misenpai.clique',
  );
}
